name: Publish Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Set version tag
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION_TAG="${SHORT_SHA}"
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/log-generator:latest
            ghcr.io/${{ github.repository_owner }}/log-generator:${{ env.VERSION_TAG }}

      - name: Post-build status
        if: always()
        run: |
          echo "Docker image published to GitHub Container Registry."
      
      - name: Checkout DeployHaven repo
        uses: actions/checkout@v3
        with:
          repository: ctrlb-hq/DeployHaven
          ref: main
          token: ${{ secrets.GHCR_PAT }}
      
      - name: Debug Environment
        run: |
          echo "VERSION_TAG: ${{ env.VERSION_TAG }}"
          echo "Working Directory: $(pwd)"
          ls -la staging/internal-apps

      - name: Update load-gen.yaml
        run: |
          sed -i "s|ghcr.io/ctrlb-hq/load-gen:.*|ghcr.io/ctrlb-hq/load-gen:${{ env.VERSION_TAG }}|" staging/internal-apps/load-gen.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add staging/internal-apps/load-gen.yaml
          git commit -m "Update load-gen image to ${{ env.VERSION_TAG }}"
          git push origin main